name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest pydantic aiosqlite pytest-asyncio pytest-benchmark

      - name: Run Ruff
        run: ruff check . --fix # Lint with Ruff and auto-fix issues

      - name: Run Black
        run: black --check .

      - name: Run Pytest
        run: pytest -v -m "not benchmark"

      - name: Benchmark Report
        if: success()  # Only run if the tests pass
        run: |
          pytest --benchmark-only --benchmark-save=ci.json

