name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest pydantic

      - name: Run Ruff
        run: ruff check . --fix # Lint with Ruff and auto-fix issues

      - name: Run Black
        run: black --check .

      - name: Run Pytest
        run: pytest -v
